change to master1

diff --git a/.github/workflows/pipeline-frontend.yml b/.github/workflows/pipeline-frontend.yml
--- a/.github/workflows/pipeline-frontend.yml
+++ b/.github/workflows/pipeline-frontend.yml
@@ -22,7 +22,13 @@ jobs:
         id: extract_version
         run: |
           cd itsm-ui
-          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT
+          VERSION=$(jq -r '.version' package.json)
+          echo "VERSION=$VERSION"
+          if [ -z "$VERSION" ]; then
+            echo "❌ VERSION not found in package.json"
+            exit 1
+          fi
+          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
 
       - name: Login to DockerHub
         uses: docker/login-action@v3
